/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency readiness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a phone and create a 7-day user session
         * @description Only verification code 000000 is accepted. The API never sends SMS.
         *     Registration succeeds only for a previously unregistered phone.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in a registered user for 7 days */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restore the current user session */
        get: operations["getUserSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current user session
         * @description Active generations started by this exact user session receive a stop
         *     request. Other sessions for the same user are not revoked.
         */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search the current user's conversations
         * @description Sorted by lastActivityAt descending then id descending. Search matches
         *     title only and trims surrounding whitespace. The client groups unsearched
         *     results into today, yesterday, recent 7 days, and earlier using
         *     Asia/Shanghai.
         */
        get: operations["listUserConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a current-user conversation summary and active generation */
        get: operations["getUserConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load messages, starting with the latest 30
         * @description Returns the requested page in chronological order. The default pageSize
         *     is 30. The client loads the last page first, then requests earlier pages.
         */
        get: operations["listUserConversationMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Persist a user message and stream a new assistant generation
         * @description conversationId is omitted for a new unsaved conversation. The first
         *     successful persistence transaction creates the conversation, temporary
         *     title, user message, assistant placeholder, generation and LLM call.
         *     clientMessageId is generated once by the browser. Repeating it for the
         *     same user returns 409 DUPLICATE_MESSAGE with the existing generationId,
         *     so the client can read authoritative state without creating another message.
         */
        post: operations["createUserGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/generations/{generationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authoritative generation state */
        get: operations["getUserGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/generations/{generationId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Idempotently request generation stop */
        post: operations["stopUserGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/assistant-messages/{assistantMessageId}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry the latest retryable failed or stopped assistant message
         * @description Reuses the original user message, creates a new assistant message,
         *     generation and LLM call, and preserves the original assistant message.
         */
        post: operations["retryAssistantMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in to the independent admin identity domain */
        post: operations["loginAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restore the current admin session */
        get: operations["getAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current admin session */
        post: operations["logoutAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/llm-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the single effective OpenAI configuration
         * @description Returns the complete API Key in plaintext to an authenticated admin.
         */
        get: operations["getAdminLlmConfig"];
        /**
         * Save and immediately activate the OpenAI API Key and model
         * @description Saving is independent from connection testing. Non-empty but invalid
         *     values may be saved and will affect subsequent chat, title and retry calls.
         */
        put: operations["saveAdminLlmConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/llm-config/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test unsaved OpenAI form values
         * @description Uses exactly the submitted API Key and model, sends no user conversation
         *     data, does not save the config, and does not create a topic LLM call record.
         */
        post: operations["testAdminLlmConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all user conversations as admin topics
         * @description Sorted by lastActivityAt descending then id descending. Date filters are
         *     inclusive calendar dates in Asia/Shanghai and are converted to UTC by
         *     the server. phone is an exact match; titleQuery is a contains match.
         */
        get: operations["listAdminTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get topic header and counts */
        get: operations["getAdminTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{topicId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all topic messages in chronological pages */
        get: operations["listAdminTopicMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{topicId}/llm-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List actual topic LLM calls in chronological order
         * @description Includes chat, title and retry calls. Prompt items preserve the actual
         *     role and order sent to the provider. The response contains actual full
         *     or partial output and provider errors. Connection tests are excluded.
         */
        get: operations["listAdminTopicLlmCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 13800138000 */
        Phone: string;
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "ok" | "unavailable";
            /** Format: date-time */
            time: string;
        };
        UserPhoneAuthRequest: {
            phone: components["schemas"]["Phone"];
            /**
             * @description MVP accepts only 000000
             * @example 000000
             */
            verificationCode: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            phone: components["schemas"]["Phone"];
            /** Format: date-time */
            createdAt: string;
        };
        UserSessionResponse: {
            user: components["schemas"]["User"];
            /** Format: date-time */
            expiresAt: string;
        };
        AdminLoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        Admin: {
            /** Format: uuid */
            id: string;
            username: string;
        };
        AdminSessionResponse: {
            admin: components["schemas"]["Admin"];
            /** Format: date-time */
            expiresAt: string;
        };
        ConversationSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            titleStatus: "temporary" | "final";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastActivityAt: string;
            messageCount: number;
        };
        ConversationPage: {
            items: components["schemas"]["ConversationSummary"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ConversationDetailResponse: {
            conversation: components["schemas"]["ConversationSummary"];
            canSend: boolean;
            activeGeneration?: components["schemas"]["Generation"] | null;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /**
             * Format: int64
             * @description Stable, strictly increasing order inside one conversation
             */
            sequence: number;
            /** @enum {string} */
            role: "user" | "assistant";
            /** @enum {string} */
            status: "persisted" | "generating" | "completed" | "failed" | "stopped";
            content: string;
            /** Format: uuid */
            replyToMessageId?: string;
            /** Format: uuid */
            retryOfMessageId?: string;
            /** Format: uuid */
            generationId?: string;
            /** @description Present for assistant messages */
            canRetry?: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            page: number;
            pageSize: number;
            total: number;
        };
        CreateGenerationRequest: {
            /**
             * Format: uuid
             * @description Omit for an unsaved new conversation
             */
            conversationId?: string;
            /**
             * Format: uuid
             * @description Stable browser-generated ID for duplicate prevention
             */
            clientMessageId: string;
            /** @description Server trims surrounding whitespace before applying the length limits */
            content: string;
        };
        RetryGenerationRequest: {
            /**
             * Format: uuid
             * @description Stable browser-generated ID used to prevent duplicate retries
             */
            clientRetryId: string;
        };
        Generation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            userMessageId: string;
            /** Format: uuid */
            assistantMessageId: string;
            /** @enum {string} */
            kind: "chat" | "retry";
            /** @enum {string} */
            status: "streaming" | "completed" | "failed" | "stopped";
            stopRequested: boolean;
            /** @enum {string|null} */
            errorCode: "LLM_NOT_CONFIGURED" | "LLM_UNAVAILABLE" | "LLM_RATE_LIMITED" | "LLM_TIMEOUT" | "RESPONSE_PARSE_FAILED" | "GENERATION_INTERRUPTED" | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GenerationResponse: {
            generation: components["schemas"]["Generation"];
            assistantMessage: components["schemas"]["Message"];
        };
        GenerationStartedEvent: {
            /** Format: uuid */
            generationId: string;
            /** Format: int64 */
            sequence: number;
            /** @enum {string} */
            kind: "chat" | "retry";
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            userMessageId: string;
            /** Format: uuid */
            assistantMessageId: string;
            temporaryTitle: string;
            /** Format: date-time */
            occurredAt: string;
        };
        GenerationDeltaEvent: {
            /** Format: uuid */
            generationId: string;
            /** Format: int64 */
            sequence: number;
            /** Format: uuid */
            assistantMessageId: string;
            delta: string;
            accumulatedLength: number;
            /** Format: date-time */
            occurredAt: string;
        };
        GenerationCompletedEvent: {
            /** Format: uuid */
            generationId: string;
            /** Format: int64 */
            sequence: number;
            generation: components["schemas"]["Generation"];
            assistantMessage: components["schemas"]["Message"];
            /** @description True when the service will attempt the non-blocking first-title call */
            titleWillBeAttempted: boolean;
            /** Format: date-time */
            occurredAt: string;
        };
        GenerationFailedEvent: {
            /** Format: uuid */
            generationId: string;
            /** Format: int64 */
            sequence: number;
            generation: components["schemas"]["Generation"];
            assistantMessage: components["schemas"]["Message"];
            error: components["schemas"]["PublicGenerationError"];
            /** Format: date-time */
            occurredAt: string;
        };
        GenerationStoppedEvent: {
            /** Format: uuid */
            generationId: string;
            /** Format: int64 */
            sequence: number;
            generation: components["schemas"]["Generation"];
            assistantMessage: components["schemas"]["Message"];
            /** @enum {string} */
            stoppedBy: "user" | "logout";
            /** Format: date-time */
            occurredAt: string;
        };
        HeartbeatEvent: {
            /** Format: uuid */
            generationId: string;
            /** Format: date-time */
            occurredAt: string;
        };
        PublicGenerationError: {
            /** @enum {string} */
            code: "LLM_NOT_CONFIGURED" | "LLM_UNAVAILABLE" | "LLM_RATE_LIMITED" | "LLM_TIMEOUT" | "RESPONSE_PARSE_FAILED" | "GENERATION_INTERRUPTED";
            message: string;
            retryable: boolean;
        };
        LlmConfigInput: {
            /** @enum {string} */
            provider: "openai";
            /** Format: password */
            apiKey: string;
            model: string;
        };
        LlmConfig: {
            /** @enum {string} */
            provider: "openai";
            /** @description Full plaintext API Key, admin-only */
            apiKey: string;
            model: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LlmConfigResponse: {
            configured: boolean;
            config?: components["schemas"]["LlmConfig"] | null;
        };
        ProviderError: {
            code?: string;
            message: string;
        };
        LlmConfigTestResponse: {
            success: boolean;
            /** @enum {string} */
            provider: "openai";
            model: string;
            providerError?: components["schemas"]["ProviderError"] | null;
            /** Format: date-time */
            testedAt: string;
        };
        AdminTopicSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            phone: components["schemas"]["Phone"];
            messageCount: number;
            llmCallCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastActivityAt: string;
        };
        AdminTopicPage: {
            items: components["schemas"]["AdminTopicSummary"][];
            page: number;
            pageSize: number;
            total: number;
        };
        AdminTopicResponse: {
            topic: components["schemas"]["AdminTopicSummary"];
        };
        AdminMessagePage: {
            items: components["schemas"]["Message"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PromptItem: {
            /** @enum {string} */
            role: "system" | "developer" | "user" | "assistant";
            content: string;
        };
        LlmCall: {
            /** Format: uuid */
            id: string;
            step: number;
            /** @enum {string} */
            callType: "chat" | "title" | "retry";
            /** Format: uuid */
            relatedMessageId?: string;
            /** @enum {string} */
            provider: "openai";
            model: string;
            prompt: components["schemas"]["PromptItem"][];
            /** @description Actual complete or partial provider output; may be empty */
            responseText: string;
            /** @enum {string} */
            status: "in_progress" | "succeeded" | "failed" | "stopped";
            providerResponseId?: string;
            providerError?: components["schemas"]["ProviderError"] | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string;
        };
        LlmCallPage: {
            items: components["schemas"]["LlmCall"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ErrorDetail: {
            field?: string;
            issue: string;
        };
        Error: {
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "INVALID_VERIFICATION_CODE" | "USER_ALREADY_EXISTS" | "USER_NOT_REGISTERED" | "INVALID_CREDENTIALS" | "UNAUTHENTICATED" | "FORBIDDEN" | "RESOURCE_NOT_FOUND" | "RATE_LIMITED" | "PAGE_INVALID" | "DATE_RANGE_INVALID" | "UNSUPPORTED_MEDIA_TYPE" | "GENERATION_IN_PROGRESS" | "RETRY_NOT_ALLOWED" | "DUPLICATE_MESSAGE" | "LLM_NOT_CONFIGURED" | "LLM_UNAVAILABLE" | "INTERNAL_ERROR";
            message: string;
            requestId: string;
            /**
             * Format: uuid
             * @description Present for DUPLICATE_MESSAGE so the client can read existing state
             */
            generationId?: string;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
    };
    responses: {
        /** @description Invalid input, verification code, page or date range */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Session is absent, expired or revoked */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHENTICATED",
                 *         "message": "登录状态已失效，请重新登录",
                 *         "requestId": "req_01"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Same-origin or authorization validation failed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "请求未获授权",
                 *         "requestId": "req_01"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource does not exist or is not owned by the current user */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RESOURCE_NOT_FOUND",
                 *         "message": "资源不存在",
                 *         "requestId": "req_01"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                /** @description Seconds until the client may retry */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "请求过于频繁，请稍后再试",
                 *         "requestId": "req_01"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description One-based page number */
        Page: number;
        PageSize: number;
        ConversationId: string;
        GenerationId: string;
        AssistantMessageId: string;
        /** @description Topic ID equals the underlying conversation ID */
        TopicId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API and required dependencies are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "database": "ok",
                     *       "time": "2026-07-16T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description API is alive but a required dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "degraded",
                     *       "database": "unavailable",
                     *       "time": "2026-07-16T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "phone": "13800138000",
                 *       "verificationCode": "000000"
                 *     }
                 */
                "application/json": components["schemas"]["UserPhoneAuthRequest"];
            };
        };
        responses: {
            /** @description User created and logged in */
            201: {
                headers: {
                    /** @description HttpOnly user session cookie scoped to /api/v1/user */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Phone is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_ALREADY_EXISTS",
                     *         "message": "该手机号已注册，请直接登录",
                     *         "requestId": "req_01"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPhoneAuthRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Phone is not registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_REGISTERED",
                     *         "message": "该手机号尚未注册，请先注册",
                     *         "requestId": "req_01"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getUserSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listUserConversations: {
        parameters: {
            query?: {
                /** @description Title contains match. Empty or omitted means grouped list. */
                query?: string;
                /** @description One-based page number */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getUserConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listUserConversationMessages: {
        parameters: {
            query?: {
                /** @description One-based page number */
                page?: components["parameters"]["Page"];
                pageSize?: number;
            };
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createUserGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGenerationRequest"];
            };
        };
        responses: {
            /**
             * @description SSE stream. The first event is generation.started, followed by zero
             *     or more generation.delta events and exactly one terminal event.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: generation.started
                     *     data: {"generationId":"2c255ae2-d891-4d6c-80c5-3d5ee1f534ca","sequence":1,"kind":"chat","conversationId":"6bf22123-6db0-4232-929d-3c77272a6ad2","userMessageId":"d5026980-61a4-4478-a045-bd2efbf17abc","assistantMessageId":"4cbe9c70-74ff-4d5c-a70f-131722b21589","temporaryTitle":"帮我写一个 Python 脚本","occurredAt":"2026-07-16T12:00:00Z"}
                     *
                     *     event: generation.delta
                     *     data: {"generationId":"2c255ae2-d891-4d6c-80c5-3d5ee1f534ca","sequence":2,"assistantMessageId":"4cbe9c70-74ff-4d5c-a70f-131722b21589","delta":"当然可以。","accumulatedLength":6,"occurredAt":"2026-07-16T12:00:01Z"}
                     */
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Active generation or duplicate clientMessageId */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            /** @description LLM configuration is missing or service unavailable before persistence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getUserGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    stopUserGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation was already terminal; current state returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Stop accepted; observe SSE or generation state for terminal result */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    retryAssistantMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assistantMessageId: components["parameters"]["AssistantMessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryGenerationRequest"];
            };
        };
        responses: {
            /** @description SSE stream with kind=retry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Message is no longer retryable or another generation is active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RETRY_NOT_ALLOWED",
                     *         "message": "该回复当前不可重试",
                     *         "requestId": "req_01"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    loginAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "username": "admin",
                 *       "password": "admin"
                 *     }
                 */
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Admin logged in */
            200: {
                headers: {
                    /** @description HttpOnly admin session cookie scoped to /api/v1/admin */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Username or password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_CREDENTIALS",
                     *         "message": "账号或密码错误",
                     *         "requestId": "req_01"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active admin session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logoutAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminLlmConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current config or unconfigured state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    saveAdminLlmConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmConfigInput"];
            };
        };
        responses: {
            /** @description Saved effective config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmConfigResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    testAdminLlmConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmConfigInput"];
            };
        };
        responses: {
            /** @description Test completed; success can be true or false */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmConfigTestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminTopics: {
        parameters: {
            query?: {
                titleQuery?: string;
                phone?: components["schemas"]["Phone"];
                createdFrom?: string;
                createdTo?: string;
                activityFrom?: string;
                activityTo?: string;
                /** @description One-based page number */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTopicPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAdminTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Topic ID equals the underlying conversation ID */
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTopicResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminTopicMessages: {
        parameters: {
            query?: {
                /** @description One-based page number */
                page?: components["parameters"]["Page"];
                pageSize?: number;
            };
            header?: never;
            path: {
                /** @description Topic ID equals the underlying conversation ID */
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMessagePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminTopicLlmCalls: {
        parameters: {
            query?: {
                /** @description One-based page number */
                page?: components["parameters"]["Page"];
                pageSize?: number;
            };
            header?: never;
            path: {
                /** @description Topic ID equals the underlying conversation ID */
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LLM call page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmCallPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
